import { LucideArrowLeft, LucideBadgeCheck, LucideBanknoteX, LucideBell, LucideBuilding, LucideBuilding2, LucideCalendarClock, LucideCalendarPlus, LucideChevronDown, LucideChevronRight, LucideCircleQuestionMark, LucideEarth, LucideEye, LucideEyeOff, LucideFactory, LucideHandCoins, LucideHouse, LucideIconData, LucideKeyRound, LucideLandmark, LucideLandPlot, LucideLayers, LucideLogIn, LucideLogOut, LucideMap, LucideMapPin, LucideMapPinHouse, LucideMapPinned, LucideMoon, LucidePanelLeftClose, LucidePanelLeftOpen, LucidePencil, LucidePlus, LucideSave, LucideShieldQuestionMark, LucideSignpost, LucideSignpostBig, LucideSquarePen, LucideSun, LucideTrendingDown, LucideTrendingUp, LucideUser, LucideUserCheck, LucideUserCog, LucideWallet, LucideX } from "@lucide/angular";

export const APP_ICONS = [
    LucideArrowLeft,
    LucideBadgeCheck,
    LucideBanknoteX,
    LucideBell,
    LucideBuilding,
    LucideBuilding2,
    LucideCalendarClock,
    LucideCalendarPlus,
    LucideChevronDown,
    LucideChevronRight,
    LucideCircleQuestionMark,
    LucideEarth,
    LucideEye,
    LucideEyeOff,
    LucideFactory,
    LucideHandCoins,
    LucideHouse,
    LucideKeyRound,
    LucideLandmark,
    LucideLandPlot,
    LucideLayers,
    LucideLogIn,
    LucideLogOut,
    LucideMap,
    LucideMapPin,
    LucideMapPinHouse,
    LucideMapPinned,
    LucideMoon,
    LucidePanelLeftClose,
    LucidePanelLeftOpen,
    LucidePencil,
    LucidePlus,
    LucideSave,
    LucideShieldQuestionMark,
    LucideSignpost,
    LucideSignpostBig,
    LucideSquarePen,
    LucideSun,
    LucideTrendingDown,
    LucideTrendingUp,
    LucideUser,
    LucideUserCheck,
    LucideUserCog,
    LucideWallet,
    LucideX
];

export const APP_ICONS_MAP: Record<string, any> = {
    ArrowLeft: LucideArrowLeft,
    BadgeCheck: LucideBadgeCheck,
    BanknoteX: LucideBanknoteX,
    Bell: LucideBell,
    Building: LucideBuilding,
    Building2: LucideBuilding2,
    CalendarClock: LucideCalendarClock,
    CalendarPlus: LucideCalendarPlus,
    ChevronDown: LucideChevronDown,
    ChevronRight: LucideChevronRight,
    CircleQuestionMark: LucideCircleQuestionMark,
    Earth: LucideEarth,
    Eye: LucideEye,
    EyeOff: LucideEyeOff,
    Factory: LucideFactory,
    HandCoins: LucideHandCoins,
    House: LucideHouse,
    KeyRound: LucideKeyRound,
    Landmark: LucideLandmark,
    LandPlot: LucideLandPlot,
    Layers: LucideLayers,
    LogIn: LucideLogIn,
    LogOut: LucideLogOut,
    Map: LucideMap,
    MapPin: LucideMapPin,
    MapPinHouse: LucideMapPinHouse,
    MapPinned: LucideMapPinned,
    Moon: LucideMoon,
    PanelLeftClose: LucidePanelLeftClose,
    PanelLeftOpen: LucidePanelLeftOpen,
    Pencil: LucidePencil,
    Plus: LucidePlus,
    Save: LucideSave,
    ShieldQuestionMark: LucideShieldQuestionMark,
    Signpost: LucideSignpost,
    SignpostBig: LucideSignpostBig,
    SquarePen: LucideSquarePen,
    Sun: LucideSun,
    TrendingDown: LucideTrendingDown,
    TrendingUp: LucideTrendingUp,
    User: LucideUser,
    UserCheck: LucideUserCheck,
    UserCog: LucideUserCog,
    Wallet: LucideWallet,
    X: LucideX
};