import {
  LucideArrowLeft,
  LucideBadgeCheck,
  LucideBadgeIndianRupee,
  LucideBanknoteCheck,
  LucideBanknoteX,
  LucideBell,
  LucideBuilding,
  LucideBuilding2,
  LucideCalendarClock,
  LucideCalendarPlus,
  LucideChevronDown,
  LucideChevronRight,
  LucideCircleQuestionMark,
  LucideCombine,
  LucideEarth,
  LucideEye,
  LucideEyeOff,
  LucideFactory,
  LucideFileUser,
  LucideGlobe,
  LucideHandCoins,
  LucideHouse,
  LucideIconData,
  LucideKeyRound,
  LucideLandmark,
  LucideLandPlot,
  LucideLayers,
  LucideLayoutDashboard,
  LucideLock,
  LucideLockOpen,
  LucideLogIn,
  LucideLogOut,
  LucideMap,
  LucideMapPin,
  LucideMapPinHouse,
  LucideMapPinned,
  LucideMoon,
  LucidePanelLeftClose,
  LucidePanelLeftOpen,
  LucidePencil,
  LucidePlus,
  LucideSave,
  LucideShieldCheck,
  LucideShieldEllipsis,
  LucideShieldQuestionMark,
  LucideSignpost,
  LucideSignpostBig,
  LucideSplit,
  LucideSquareMenu,
  LucideSquarePen,
  LucideSquareUserRound,
  LucideSummary,
  LucideSun,
  LucideTrendingDown,
  LucideTrendingUp,
  LucideUser,
  LucideUserCheck,
  LucideUserCog,
  LucideUserKey,
  LucideUsers,
  LucideWallet,
  LucideX,
  LucideSearch,
  LucideFunnel,
  LucideReceiptText,
  LucideCheck,
  LucidePiggyBank,
  LucideShieldPlus,
  LucideTag,
  LucideLayoutGrid,
  LucideListOrdered,
  LucideArrowRight,
  LucideCode,
  LucideSettings,
  LucideCalendarCheck,
  LucideCalendar1,
  LucideBanknoteArrowUp,
  LucideBanknoteArrowDown,
  LucideRotateCcw,
  LucideFileDown,
  LucideEllipsisVertical,
  LucideHeart,
  LucideDroplet,
  LucideVenus,
  LucideFlag,
  LucideChessBishop,
  LucideMars,
  LucideStickyNote,
  LucideChevronLeft,
  LucideIdCardLanyard,
  LucideSwatchBook,
  LucideClipboardCheck,
  LucideAccessibility,
  LucideRoad,
  LucideMapPinSearch,
  LucideHousePlus,
  LucideSiren,
  LucideLampDesk,
  LucideDownload,
  LucideNotebookText,
  LucideCoins,
  LucideTriangleAlert,
  LucidePhone,
  LucideMail,
  LucideUserRound,
  LucideNotebookTabs,
  LucideHeadset,
  LucideTrash2,
  LucideWarehouse,
  LucideHash,
  LucideLocateFixed,
  LucideRoute,
  LucideBus,
  LucideTrainFront,
  LucideSignal,
  LucideWifi,
  LucideZap,
  LucideDroplets,
  LucideBriefcase,
  LucideWheat,
  LucideBeef,
  LucideStore,
  LucideShoppingBag,
  LucideTruck,
  LucideHardHat,
  LucidePlusCircle,
  LucideGauge,
  LucideTarget,
  LucideUsersRound,
  LucideCarFront,
  LucideBike,
  LucideCreditCard,
  LucideSmartphone,
  LucideSwords,
  LucideShieldAlert,
  LucideCloudRain,
  LucideWind,
  LucideMountain,
  LucideRepeat,
  LucideSearchCheck,
  LucideCamera,
  LucideThumbsUp,
  LucidePercent,
  LucideBookOpen,
  LucideIndianRupee,
  LucideSend,
} from '@lucide/angular';

export const APP_ICONS = [
  LucideArrowLeft,
  LucideBadgeCheck,
  LucideBadgeIndianRupee,
  LucideBanknoteCheck,
  LucideBanknoteX,
  LucideBell,
  LucideBuilding,
  LucideBuilding2,
  LucideCalendarClock,
  LucideCalendarPlus,
  LucideChevronDown,
  LucideChevronRight,
  LucideChevronLeft,
  LucideCircleQuestionMark,
  LucideCoins,
  LucideCombine,
  LucideEarth,
  LucideEye,
  LucideEyeOff,
  LucideFactory,
  LucideFileUser,
  LucideGlobe,
  LucideHandCoins,
  LucideHouse,
  LucideKeyRound,
  LucideLandmark,
  LucideLandPlot,
  LucideLayers,
  LucideLayoutDashboard,
  LucideLogIn,
  LucideLogOut,
  LucideMap,
  LucideMapPin,
  LucideMapPinHouse,
  LucideMapPinned,
  LucideMoon,
  LucidePanelLeftClose,
  LucidePanelLeftOpen,
  LucidePencil,
  LucidePlus,
  LucideSave,
  LucideShieldCheck,
  LucideShieldEllipsis,
  LucideShieldQuestionMark,
  LucideSignpost,
  LucideSignpostBig,
  LucideSplit,
  LucideSquareMenu,
  LucideSquarePen,
  LucideSquareUserRound,
  LucideSummary,
  LucideSun,
  LucideTrendingDown,
  LucideTrendingUp,
  LucideUser,
  LucideUserCheck,
  LucideUserCog,
  LucideUserKey,
  LucideUsers,
  LucideWallet,
  LucideX,
  LucideLock,
  LucideLockOpen,
  LucideSearch,
  LucideFunnel,
  LucideReceiptText,
  LucideCheck,
  LucidePiggyBank,
  LucideShieldPlus,
  LucideTag,
  LucideLayoutGrid,
  LucideListOrdered,
  LucideArrowRight,
  LucideCode,
  LucideSettings,
  LucideCalendarCheck,
  LucideCalendar1,
  LucideBanknoteArrowUp,
  LucideBanknoteArrowDown,
  LucideRotateCcw,
  LucideFileDown,
  LucideEllipsisVertical,
  LucideHeart,
  LucideDroplet,
  LucideVenus,
  LucideFlag,
  LucideChessBishop,
  LucideMars,
  LucideStickyNote,
  LucideIdCardLanyard,
  LucideSwatchBook,
  LucideClipboardCheck,
  LucideAccessibility,
  LucideRoad,
  LucideMapPinSearch,
  LucideHousePlus,
  LucideSiren,
  LucideLampDesk,
  LucideDownload,
  LucideEllipsisVertical,
  LucideNotebookText,
  LucideTriangleAlert,
  LucidePhone,
  LucideMail,
  LucideUserRound,
  LucideNotebookTabs,
  LucideHeadset,
  LucideWarehouse,
  LucideTrash2,
  LucideHash,
  LucideLocateFixed,
  LucideRoute,
  LucideBus,
  LucideTrainFront,
  LucideSignal,
  LucideWifi,
  LucideZap,
  LucideDroplets,
  LucideBriefcase,
  LucideWheat,
  LucideBeef,
  LucideStore,
  LucideShoppingBag,
  LucideTruck,
  LucideHardHat,
  LucidePlusCircle,
  LucideGauge,
  LucideTarget,
  LucideUsersRound,
  LucideCarFront,
  LucideBike,
  LucideCreditCard,
  LucideSmartphone,
  LucideSwords,
  LucideShieldAlert,
  LucideCloudRain,
  LucideWind,
  LucideMountain,
  LucideRepeat,
  LucideSearchCheck,
  LucideCamera,
  LucideThumbsUp,
  LucidePercent,
  LucideBookOpen,
  LucideIndianRupee,
  LucideSend,
];

export const APP_ICONS_MAP: Record<string, any> = {
  ArrowLeft: LucideArrowLeft,
  BadgeCheck: LucideBadgeCheck,
  BadgeIndianRupee: LucideBadgeIndianRupee,
  BanknoteCheck: LucideBanknoteCheck,
  BanknoteX: LucideBanknoteX,
  Bell: LucideBell,
  Building: LucideBuilding,
  Building2: LucideBuilding2,
  CalendarClock: LucideCalendarClock,
  CalendarPlus: LucideCalendarPlus,
  ChevronDown: LucideChevronDown,
  ChevronRight: LucideChevronRight,
  CircleQuestionMark: LucideCircleQuestionMark,
  Coins: LucideCoins,
  Combine: LucideCombine,
  Earth: LucideEarth,
  Eye: LucideEye,
  EyeOff: LucideEyeOff,
  Factory: LucideFactory,
  FileUser: LucideFileUser,
  Globe: LucideGlobe,
  HandCoins: LucideHandCoins,
  House: LucideHouse,
  KeyRound: LucideKeyRound,
  Landmark: LucideLandmark,
  LandPlot: LucideLandPlot,
  Layers: LucideLayers,
  LayoutDashboard: LucideLayoutDashboard,
  LogIn: LucideLogIn,
  LogOut: LucideLogOut,
  Map: LucideMap,
  MapPin: LucideMapPin,
  MapPinHouse: LucideMapPinHouse,
  MapPinned: LucideMapPinned,
  Moon: LucideMoon,
  PanelLeftClose: LucidePanelLeftClose,
  PanelLeftOpen: LucidePanelLeftOpen,
  Pencil: LucidePencil,
  Plus: LucidePlus,
  Save: LucideSave,
  ShieldCheck: LucideShieldCheck,
  ShieldEllipsis: LucideShieldEllipsis,
  ShieldQuestionMark: LucideShieldQuestionMark,
  Signpost: LucideSignpost,
  SignpostBig: LucideSignpostBig,
  Split: LucideSplit,
  SquareMenu: LucideSquareMenu,
  SquarePen: LucideSquarePen,
  SquareUserRound: LucideSquareUserRound,
  Summary: LucideSummary,
  Sun: LucideSun,
  TrendingDown: LucideTrendingDown,
  TrendingUp: LucideTrendingUp,
  User: LucideUser,
  UserCheck: LucideUserCheck,
  UserCog: LucideUserCog,
  UserKey: LucideUserKey,
  Users: LucideUsers,
  Wallet: LucideWallet,
  X: LucideX,
  Lock: LucideLock,
  LockOpen: LucideLockOpen,
  Search: LucideSearch,
  Funnel: LucideFunnel,
  ReceiptText: LucideReceiptText,
  Check: LucideCheck,
  PiggyBank: LucidePiggyBank,
  ShieldPlus: LucideShieldPlus,
  Tag: LucideTag,
  LayoutGrid: LucideLayoutGrid,
  ListOrdered: LucideListOrdered,
  ArrowRight: LucideArrowRight,
  Code: LucideCode,
  Settings: LucideSettings,
  CalendarCheck: LucideCalendarCheck,
  Calendar1: LucideCalendar1,
  BanknoteArrowUp: LucideBanknoteArrowUp,
  BanknoteArrowDown: LucideBanknoteArrowDown,
  RotateCcw: LucideRotateCcw,
  FileDown: LucideFileDown,
  EllipsisVertical: LucideEllipsisVertical,
  Heart: LucideHeart,
  Droplet: LucideDroplet,
  Venus: LucideVenus,
  Flag: LucideFlag,
  ChessBishop: LucideChessBishop,
  Mars: LucideMars,
  StickyNote: LucideStickyNote,
  ChevronLeft: LucideChevronLeft,
  IdCardLanyard: LucideIdCardLanyard,
  SwatchBook: LucideSwatchBook,
  ClipboardCheck: LucideClipboardCheck,
  Accessibility: LucideAccessibility,
  Road: LucideRoad,
  MapPinSearch: LucideMapPinSearch,
  HousePlus: LucideHousePlus,
  Siren: LucideSiren,
  Lampdesk: LucideLampDesk,
  Download: LucideDownload,
  NotebookText: LucideNotebookText,
  TriangleAlert: LucideTriangleAlert,
  Phone: LucidePhone,
  Email: LucideMail,
  UserRound: LucideUserRound,
  NotebookTabs: LucideNotebookTabs,
  Headset: LucideHeadset,
  WareHouse: LucideWarehouse,
  Trash2: LucideTrash2,
  Hash: LucideHash,
  LocateFixed: LucideLocateFixed,
  Route: LucideRoute,
  Bus: LucideBus,
  TrainFront: LucideTrainFront,
  Signal: LucideSignal,
  Wifi: LucideWifi,
  Zap: LucideZap,
  Droplets: LucideDroplets,
  Briefcase: LucideBriefcase,
  Wheat: LucideWheat,
  Beef: LucideBeef,
  Store: LucideStore,
  ShoppingBag: LucideShoppingBag,
  Truck: LucideTruck,
  HardHat: LucideHardHat,
  PlusCircle: LucidePlusCircle,
  Gauge: LucideGauge,
  Target: LucideTarget,
  UsersRound: LucideUsersRound,
  CarFront: LucideCarFront,
  Bike: LucideBike,
  CreditCard: LucideCreditCard,
  Smartphone: LucideSmartphone,
  Swords: LucideSwords,
  ShieldAlert: LucideShieldAlert,
  CloudRain: LucideCloudRain,
  Wind: LucideWind,
  Mountain: LucideMountain,
  Repeat: LucideRepeat,
  SearchCheck: LucideSearchCheck,
  Camera: LucideCamera,
  ThumbsUp: LucideThumbsUp,
  Percent: LucidePercent,
  BookOpen: LucideBookOpen,
  IndianRupee: LucideIndianRupee,
  Send: LucideSend,
};
